# Cognitive System Configuration
# 
# This file defines the configuration for INGENIO-1 Cognitive Agent
# and the broader cognitive engineering system.

# Agent Configuration
agent:
  name: "INGENIO-1"
  level: 4  # Cognitive System
  version: "1.0.0"
  mission: "Software 3.0 Engineering Excellence"
  framework: "Three Pillars Quest Engine"

# Processing Configuration
processing:
  # Issue processing settings
  issue_processing:
    batch_size: 50
    concurrent_limit: 5
    retry_attempts: 3
    skip_existing: true
    force_regeneration: false
  
  # Cognitive analysis settings
  cognitive_analysis:
    pattern_threshold: 0.3
    concept_extraction_depth: 5
    meta_learning_enabled: true
    recursive_improvement: true
  
  # Spec generation settings
  spec_generation:
    format: "markdown"
    template_version: "2.0"
    include_etymology: true
    include_three_pillars: true
    include_cognitive_enhancement: true
    include_meta_learning: true

# Three Pillars Quest Engine Configuration
three_pillars:
  clear_strategy:
    enabled: true
    phases: ["vision", "design", "sprint", "daily"]
    focus_areas: ["goals", "coherent_action", "exit_strategy"]
  
  intrinsic_drive:
    enabled: true
    components: ["mastery", "autonomy", "purpose"]
    vs_extrinsic: true
  
  contextual_awareness:
    enabled: true
    principles: ["it_depends", "documentation", "observability", "communication"]
    feedback_loops: true

# Software 3.0 Configuration
software_3_0:
  cognitive_agents:
    enabled: true
    collaboration_mode: "human_cognitive_teams"
    autonomy_level: "supervised_autonomous"
    learning_mode: "meta_learning"
  
  engineering_excellence:
    focus_areas: ["quality", "collaboration", "documentation", "meta_learning"]
    recursive_improvement: true
    behavior_alignment: true

# Session Management Configuration
session_management:
  # Session tracking
  session_id_format: "%Y-%m-%d_%H%M%S_cognitive_ci"
  session_directory: "experiments/cognitive_sessions"
  context_preservation: true
  restart_capability: true
  
  # Logging configuration
  logging:
    level: "info"
    include_cognitive_trace: true
    include_decision_chains: true
    include_meta_insights: true
  
  # Archive settings
  archive:
    retention_days: 90
    include_artifacts: true
    compress_sessions: false

# Output Configuration
output:
  # Spec generation
  specs:
    directory: "specs"
    structure: "issue_based"
    naming_convention: "snake_case"
    
  # Documentation
  documentation:
    auto_generate: true
    include_cognitive_traces: true
    include_meta_learning: true
    format: "markdown"

# Integration Configuration
integration:
  # GitHub integration
  github:
    auto_commit: true
    commit_message_format: "feat(cognitive): {action} - {summary}"
    branch_strategy: "current_branch"
    pr_creation: false
  
  # Workflow integration
  workflows:
    trigger_on_issue_events: true
    trigger_on_schedule: true
    manual_trigger_enabled: true
    force_all_option: true

# Cognitive Enhancement Configuration
cognitive_enhancement:
  # Pattern recognition
  pattern_recognition:
    enabled: true
    learning_rate: 0.1
    pattern_library_update: true
    
  # Meta-learning
  meta_learning:
    enabled: true
    recursive_improvement: true
    cross_session_learning: true
    knowledge_transfer: true
  
  # Collaboration protocols
  collaboration:
    human_cognitive_teams: true
    async_communication: true
    transparency_level: "full"
    audit_capability: true

# Quality Configuration
quality:
  # Validation settings
  validation:
    spec_completeness_check: true
    three_pillars_validation: true
    cognitive_enhancement_check: true
    etymology_validation: true
  
  # Improvement settings
  improvement:
    continuous_improvement: true
    feedback_integration: true
    recursive_enhancement: true
    meta_quality_metrics: true

# Error Handling Configuration
error_handling:
  retry_strategy: "exponential_backoff"
  fallback_mode: "minimal_spec_generation"
  error_reporting: "detailed"
  recovery_procedures: true

# Experimental Configuration
experimental:
  # New capabilities being tested
  multi_agent_collaboration: false
  dynamic_learning: false
  cross_repository_learning: false
  emergent_intelligence: false
  
  # A/B testing
  ab_testing:
    enabled: false
    split_ratio: 0.5
    metrics_collection: true

# Security Configuration
security:
  # Access control
  access_control:
    require_authentication: true
    permission_levels: ["read", "write", "admin"]
    audit_logging: true
  
  # Data protection
  data_protection:
    encrypt_sensitive_data: false
    anonymize_personal_info: true
    secure_storage: true

---
# Configuration Metadata
metadata:
  version: "1.0.0"
  last_updated: "2024-12-19"
  maintained_by: "INGENIO-1 Cognitive Agent"
  framework: "Three Pillars Quest Engine"
  mission: "Software 3.0 Engineering Excellence"