name: Cognitive Issue Processor

on:
  issues:
    types: [opened, edited, labeled]
  schedule:
    # Run every hour to continuously process open issues
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_all:
        description: 'Force process all issues'
        required: false
        default: 'false'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  cognitive-processing:
    runs-on: ubuntu-latest
    name: Process Issues with Cognitive Agent
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: |
        npm init -y
        npm install @octokit/rest yaml fs-extra
    
    - name: Process Issues with Cognitive Agent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        TRIGGERED_BY: ${{ github.event_name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        FORCE_ALL: ${{ github.event.inputs.force_all }}
      run: |
        node .github/scripts/cognitive-processor.js
    
    - name: Create Progress Report
      run: |
        echo "## 🧠 Cognitive Processing Report" > cognitive_report.md
        echo "" >> cognitive_report.md
        echo "**Session**: $(date +%Y-%m-%d_%H%M%S)" >> cognitive_report.md
        echo "**Agent**: INGENIO-1" >> cognitive_report.md
        echo "**Trigger**: ${{ github.event_name }}" >> cognitive_report.md
        echo "**Filter**: Only issues with 'sos oficial' label" >> cognitive_report.md
        echo "" >> cognitive_report.md
        echo "### Analysis Results" >> cognitive_report.md
        echo "- **Issues Processed**: $(find specs/ -name "VISION.md" | wc -l)" >> cognitive_report.md
        echo "- **Specs Generated**: $(find specs/ -type f -name "*.md" | wc -l)" >> cognitive_report.md
        echo "- **Pull Requests Created**: Automatic PR creation for each processed issue" >> cognitive_report.md
        echo "- **Cognitive Sessions**: $(find experiments/cognitive_sessions/ -type d -name "*_*" | wc -l)" >> cognitive_report.md
        echo "" >> cognitive_report.md
        echo "### Meta-Learning Insights" >> cognitive_report.md
        echo "- Applied Three Pillars Quest Engine consistently" >> cognitive_report.md
        echo "- Enhanced spec-driven development methodology" >> cognitive_report.md
        echo "- Maintained cognitive context for future sessions" >> cognitive_report.md
        echo "- Implemented PR-based workflow for better code review" >> cognitive_report.md
        echo "" >> cognitive_report.md
        echo "### Workflow Improvements" >> cognitive_report.md
        echo "- ✅ **Label Filtering**: Only processes issues with 'sos oficial' tag" >> cognitive_report.md
        echo "- ✅ **PR Creation**: Creates pull requests instead of direct commits" >> cognitive_report.md
        echo "- ✅ **Branch Management**: Dedicated branches for each specification" >> cognitive_report.md
        echo "- ✅ **Review Process**: Enables human review before merging specs" >> cognitive_report.md
        echo "" >> cognitive_report.md
        echo "🚀 **Status**: Cognitive processing complete - PRs ready for review"
        
        cat cognitive_report.md
    
    - name: Archive Cognitive Session
      uses: actions/upload-artifact@v4
      with:
        name: cognitive-session-${{ github.run_number }}
        path: |
          experiments/cognitive_sessions/
          specs/
          cognitive_report.md
        retention-days: 90